### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by jsg2021**
This is a pass at cleaning up and modernizing, and making it a little more performant (not using statSync) This also drops old nodes and webpack less than 2.

This includes my previous PR too.

### CODE REVIEW

**Comment by jsg2021** [comment]
Reopen if you want, but I'm just going to use my fork.

**Comment by deepsweet** [comment]
Would you like to become a maintainer?

**Comment by jsg2021** [comment]
I'm migrating away from baggage-imports, in favor of explicit imports... so I will eventually not be using this. But I would maintain it while I use it.

**Comment by deepsweet** [comment]
I've added you to collaborators, please ping me with your NPM username if you have something to publish.

**Pull request closed without merging**
